version: 2

general:
  branches:
    only:
      - master
      - develop

jobs:
  build:
    working_directory: ~/product-service

    docker:
      - image: circleci/openjdk:8u181-jdk

    environment:
      JVM_OPTS: -Xmx2g

    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Run tests
          command: ./gradlew clean test integrationTest